version: '3.8'

services:
  backend:
    container_name: crud_app
    build:
      dockerfile: Dockerfile
#    volumes:
#      - .:/go/src/github.com/Viquad/crud-app
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    container_name: crud_app_db
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
  
  migrate: &basemigrate
    profiles: ["migrate"]
    image: migrate/migrate
    entrypoint: "migrate -database postgresql://postgres:qwerty123@db:5432/postgres?sslmode=disable -path /tmp/migrations"
    command: up
    links:
      - db
    volumes:
      - ./schema:/tmp/migrations

  create-migration:
    <<: *basemigrate
    entrypoint: migrate create -dir /tmp/migrations -ext sql
    command: ""

  migrate-drop:
    <<: *basemigrate
    command: drop

  swag-init:
    profiles: ["swag"]
    image: denisgl/swag:1.6.7
    working_dir: /app
    entrypoint: "/root/swag init -g ./internal/app/app.go"
    volumes: 
      - .:/app
