db:
  host: "db"
  port: "5432"
  username: "postgres"
  db_name: "postgres"
  ssl_mode: "disable"
  connection:
    attempts: 10
    wait: 1s

cache:
  ttl: 10s

auth:
  access_ttl: 15m
  refresh_ttl: 60m
