basePath: /
definitions:
  domain.Account:
    properties:
      balance:
        type: integer
      currency:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      lastUpdate:
        type: string
    required:
    - balance
    - currency
    - firstName
    - lastName
    type: object
  domain.AccountUpdateInput:
    properties:
      balance:
        type: integer
      currency:
        type: string
      firstName:
        type: string
      lastName:
        type: string
    type: object
  rest.errorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for CRUD application
  title: CRUD app API
  version: "1.0"
paths:
  /account:
    get:
      consumes:
      - application/json
      description: Get all accounts list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Account'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.errorResponse'
      summary: Get accounts
      tags:
      - account
    post:
      consumes:
      - application/json
      description: Create new account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Account'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.errorResponse'
      summary: Create new account
      tags:
      - account
    put:
      consumes:
      - application/json
      description: Create new account
      parameters:
      - description: account info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.Account'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.errorResponse'
      summary: Create new account
      tags:
      - account
  /account/{id}:
    delete:
      consumes:
      - application/json
      description: Delete account by id
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.errorResponse'
      summary: Delete account
      tags:
      - account
    get:
      consumes:
      - application/json
      description: Get account by id
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.errorResponse'
      summary: Get account
      tags:
      - account
    post:
      consumes:
      - application/json
      description: Update account info by id
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      - description: account update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.AccountUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.errorResponse'
      summary: Update account
      tags:
      - account
    put:
      consumes:
      - application/json
      description: Update account info by id
      parameters:
      - description: account id
        in: path
        name: id
        required: true
        type: string
      - description: account update info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/domain.AccountUpdateInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Account'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.errorResponse'
      summary: Update account
      tags:
      - account
swagger: "2.0"
